### ISSUE TITLE
Post mathod or Get mathod sending value twice

### ISSUE THREAD

**Issue by vikasg603** [mathjax/MathJax-third-party-extensions#34]
when i am trying to use this extension it working but when user fill form and click submit button on target page when we seeing GET values i am seeing 2 GET value of same name 1 is null and another is typed value so that is why PHP or JAVASCRIPT is unable to see value
please fix it

**Comment by pkra** [comment]
It's unclear which extension you are referring to. Also, please provide a live sample exhibiting the issue.

**Comment by vikasg603** [comment]
http://localhost/sample.php?name=value&name=&submit=Find+Sum+of+n+terms
i am receiving this type link after submitting form check on there are 2 value of same name 1st value of name is value and another 1 is NULL

**Comment by pkra** [comment]
> http://localhost/sample.php?name=value&name=&submit=Find+Sum+of+n+terms

I'm afraid that's not a viable link outside of your local machine.

**Comment by vikasg603** [comment]
i understood what are you saying but i tried it on my websites too but not working there also
i want value of name on PHP $_GET["name"] but after submitting form php giving error 
i am not getting value entered by user 
i also tried mathml form method but same result 
check link after submitting form
http://localhost/sample.php?**name**=value&**name**=&submit=Find+Sum+of+n+terms
there are 2 veriable of same name
in my form only mathjax input field is available

**Comment by pkra** [comment]
Without more information and a live sample, it's hard to help.

You might want to consider a more general forum such as stackoverflow.
