### ISSUE TITLE
[siunitx] Support for sisetup and DeclareSIUnit

### ISSUE THREAD

**Issue by Cumol** [mathjax/MathJax-third-party-extensions#37]
Just wondering if sisetup and DeclareSIUnit are supported.  Because I cannot figure out how to make them work.

Specifically in my case:

`#+latex_header: \DeclareSIUnit\Molar{\textsc{m}}`
`#+latex_header: \sisetup{per-mode=symbol}`

**Comment by pkra** [comment]
cc @burnpanck (who wrote the extension)

**Comment by burnpanck** [comment]
If I remember correctly, they are not yet supported. However, it should not be too difficult, and again, if I remember correctly, I did prepare many of the requirements already. However, I probably won't have time to complete this anytime soon.

**Comment by pkra** [comment]
@burnpanck thanks for the comment. Where should we direct potential contributors?

**Comment by pkra** [comment]
Closing in favor of upstream https://github.com/burnpanck/MathJax-siunitx/issues/4
