### ISSUE TITLE
[siunitx] \percent not working

### ISSUE THREAD

**Issue by SamThilmany** [mathjax/MathJax-third-party-extensions#38]
I just noticed that the `\percent` command doesn't work properly in this MathJax extension, while it perfectly works in the "true" LaTeX package.

Here is my command and it's error:

`\SI{95}{/percent}
`

> Error: undefined is not an object (evaluating 'n.apply')
> file: https://cdn.mathjax.org/mathjax/2.7-latest/jax/input/TeX/jax.js?V=2.7.0
line: 19
> Debugging tips: use 'unpacked/MathJax.js', inspect 'MathJax.Hub.lastError' in the browser console

I hope it helps in resolving the bug. For any more details, you can contact me.

**Comment by pkra** [comment]
cc @burnpanck (who wrote the extension)

**Comment by SamThilmany** [comment]
@burnpanck There is also a problem with `\degreeCelsius`. The command works, but the output is weird. It's very small and it does not use the correct font.

Take a look at the screenshot. The first line is `\SI{25}{\degreeCelsius}`, the second line is simple text inside the MathJax environment `\text{25 °C}`.

![bildschirmfoto 2017-03-14 um 11 04 04](https://cloud.githubusercontent.com/assets/20460039/23895525/54aba3c4-08a6-11e7-8759-a3867d63bc33.jpg)

**Comment by burnpanck** [comment]
Hm. The `\precent` definitely is a bug. Maybe I get around to look at it this weekend. For the degree Celsius, one would have to compare the generated Jax. However, I am not an expert on that side, in fact I'm not sure if any of the units is really rendered correctly.

**Comment by pkra** [comment]
> For the degree Celsius, one would have to compare the generated Jax. 

You currently generate 

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mn>25</mn>
  <mspace width="mediummathspace" />
  <mi mathvariant="normal">&#x2103;<!-- ℃ --></mi>
</math>
```

Which seems the right way. 

However, the issue described above stems from the fact that not all fonts supported by MathJax have a glyph for ℃  (in particular the default fonts don't) and the system fallback font in the above screenshot is doing rather poorly. (It might actually be considered though a bug @SamThilmany if you can provide more info).

Alternatives could be `$\mathrm{°C}$` and (as MathML) `<math><mmultiscripts><mi mathvariant='normal'>C</mi><mprescripts><none></none><mi>&#176;</mi></mprescripts></mmultiscripts></math>`.

**Comment by pkra** [comment]
Closining favor of https://github.com/burnpanck/MathJax-siunitx/issues/3
