### ISSUE TITLE
[IMPORTANT] MathJax CDN end-of-life & suggested changes to third-party extensions

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-third-party-extensions#39]
As you may have heard, will be shutting down the CDN hosting at cdn.mathjax.org on April 30, cf. https://www.mathjax.org/cdn-shutting-down/.

As part of this, we need to migrate the third party extensions to a different setup.

We decided that the current repository structure will be retired in favor of separate repositories (one per extensions). 

This repository will continue to provide documentation on existing third party extensions.

## Suggested changes for maintainers

* Create a separate repository for your extension
  * If you're worknig on a fork of this repository, you can trim your fork, e.g., [using this guide](https://help.github.com/articles/removing-sensitive-data-from-a-repository/).
* Update the `loadComplete` calls to individual prefixes,
  * Please don't use `[Contrib]` but use unique prefixes such as `[MyExtension]`
  * Note: a clash of your prefix with another extension's prefix will usually mean that people can't use both extensions at the same time.
* Tag individual releases to allow version specific loading.
* Submit your extensions to a free CDN such as cdnjs or jsdelivr 
  * alternatively extensions can be loaded from rawgit.com

**Comment by pkra** [comment]
Updated extensions:

* https://github.com/mhchem/MathJax-mhchem
* https://github.com/pkra/mathjax-img/

**Comment by pkra** [comment]
https://github.com/Edraak/arabic-mathjax-dev has been updated and can be used with, e.g., rawgit now.

**Comment by burnpanck** [comment]
Actually, there is a better guide on how to create a separate repository using `git filter-branch`:
 [Splitting a subfolder out into a new repository](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/). The link posted in the original issue description explains how to remove particular files from a repository using `git filter-branch`.

**Comment by pkra** [comment]
siunitx has been updated and move to https://github.com/burnpanck/MathJax-siunitx

**Comment by ickc** [comment]
In light of this, I probably will retire my `physics.js`.

It started out 2.5 yrs ago to port the commands used in the Physics package to MathJax, using only macros. But I then realized something cannot be done without truly learning Javascript, and I don't see myself learning it in the near future.

And then I don't think the Physics package is popular at all. If anyone else is using the `physics.js`, please let me know, but I think I'm the only user of it. And even in the LaTeX world, it isn't really a popular package (I haven't met any other people using it except in the project I started so the others have to...). Well, another indication is if this is truly useful to anyone, some Javascript programmers probably would have already contributed and fill in the missing features.

Lastly, if I understand it correctly, these 3rd party extensions will not be centralized anymore, right? I'd like to hear more about this, especially how to catalog the 3rd party extensions together for discovery. I'd imagine it would be much easier if there's a centralized GitHub Organization for these 3rd party repositories than everyone hosting on their own. Alternatively, at least <http://docs.mathjax.org/en/latest/options/ThirdParty.html> should keep a record of it. Personally, I wouldn't use anything that doesn't have an official recognition. And also, this repository is how I discovered the siunitx MathJax package.

**Comment by pkra** [comment]
> And then I don't think the Physics package is popular at all. If anyone else is using the physics.js, please let me know, but I think I'm the only user of it. And even in the LaTeX world, it isn't really a popular package (I haven't met any other people using it except in the project I started so the others have to...). Well, another indication is if this is truly useful to anyone, some Javascript programmers probably would have already contributed and fill in the missing features.

I would like to encourage you to post to the [MathJax User Group](https://groups.google.com/d/forum/mathjax-users) to announce that you are looking for somebody to take maintenance over the project.

> Lastly, if I understand it correctly, these 3rd party extensions will not be centralized anymore, right? 

There won't be centralized hosting anymore but the README in this repo documents well-known third party extensions.

> Personally, I wouldn't use anything that doesn't have an official recognition. 

Third party extensions never had any official standing. We do not provide any guarantees on the code nor do we provide any kind of end-user support for them (we do try to help their developers where we can).

**Comment by pkra** [comment]
Closing this since it should now be old news.
