### ISSUE TITLE
[siunitx] Typesetting uncertainties in scientific notation

### ISSUE THREAD

**Issue by padawanphysicist** [mathjax/MathJax-third-party-extensions#41]
The following works just fine in LaTeX:
```
\SI{1}{\electronvolt} = \SI{1.602176621(98)e-19}{\joule}
```
However, when rendered using MathJax I have
```
1 eV = 1.602176621(98)e - 19 J
```
Where `e - 19` shows up instead of the `\times` usual scientific notation. The package works fine when using regular decimals though.

To render properly I had to use the following workaround:
```
\SI{1}{\electronvolt} = \num{1.602176621(98)}\times 10^{-19}\,\si{\joule}
```
Is there a way to typeset this properly? I couldn't find anything similar in the [package reference](http://rawgit.com/burnpanck/MathJax-siunitx/master/examples/siunitx.dtx.html).

**Comment by pkra** [comment]
You might want to file this issue at https://github.com/burnpanck/MathJax-siunitx.

**Comment by padawanphysicist** [comment]
Thanks for the advice! Sorry for the noise here. I'm closing this issue =)
