### ISSUE TITLE
Suggest replacing burnpanck/MathJax-siunitx with limefrogyank/siunitx-pcc (or adding it to the list)

### ISSUE THREAD

**Issue by solarchemist** [mathjax/MathJax-third-party-extensions#47]
[limefrogyank/siunitx-pcc](https://github.com/limefrogyank/siunitx-pcc) supports **siunitx v3** with **MathJax v3**, which represents a major improvement in my estimation.

**Comment by dpvc** [comment]
We are aware of that project, and have been working with its author toward making it available in MathJax v4.

**Comment by solarchemist** [comment]
Oh, I wasn't even aware MathJax v4 was close to release :-) 
Kudos to everyone involved!
